### ISSUE TITLE
How to enable acl.

### ISSUE THREAD

**Issue by Zqlucifer** [firealarmss/MMDVM_Reflector#5]
Hi there,I have enabled acl in config.yml file

> reflectors:
  p25:
    enabled: true # Enable or disable P25.
    acl: true # Access Control enabled on this mode.
    networkPort: 41000 # Port to bind the reflector to.
    networkTimeout: 3600000 # Timeout for peer inactivity. (Default 1 hour)
    networkDebug: false # Debug P25

And editedt he acl.yml file like this.

>  - allowed: true
      callsign: KK7MUV
      rid: 3204184

But cannot receive anything after pressing TX. After disabling acl, everything works fine.

Used DroidStar.

**Comment by firealarmss** [comment]
Are you able to provide some logs when you try to TX?

**Comment by Zqlucifer** [comment]
logs:

> Nov 09 01:53:39 s7924 MMDVM_Reflector[278249]: [01:53:39 DBG] P25: Received data from 36.21.212.37:55740:
Nov 09 01:53:39 s7924 MMDVM_Reflector[278249]:         DUMP 0000:  6D 00 00 00 00 C2 7D 57 98 EF A7 80 0E BF F2 44    *m     }W       D*
Nov 09 01:53:39 s7924 MMDVM_Reflector[278249]:         DUMP 0010:  02                                                 * *
Nov 09 01:53:39 s7924 MMDVM_Reflector[278249]: [01:53:39 DBG] P25: Received data from 36.21.212.37:55740:
Nov 09 01:53:39 s7924 MMDVM_Reflector[278249]:         DUMP 0000:  6E 00 00 00 00 CA 7F 9D B3 36 D7 80 06 FE 7F FE    *n        6      *
Nov 09 01:53:39 s7924 MMDVM_Reflector[278249]:         DUMP 0010:  02                                                 * *
Nov 09 01:53:39 s7924 MMDVM_Reflector[278249]: [01:53:39 DBG] P25: Received data from 36.21.212.37:55740:
Nov 09 01:53:39 s7924 MMDVM_Reflector[278249]:         DUMP 0000:  6F 00 00 00 00 CE 57 E4 FF 15 EB FF CE 7D EF 34    *o     W      } 4*
Nov 09 01:53:39 s7924 MMDVM_Reflector[278249]:         DUMP 0010:  02                                                 * *
Nov 09 01:53:39 s7924 MMDVM_Reflector[278249]: [01:53:39 DBG] P25: Received data from 36.21.212.37:55740:
Nov 09 01:53:39 s7924 MMDVM_Reflector[278249]:         DUMP 0000:  70 80 00 00 00 CE 6E FA 86 99 BE FF 0B 13 F5 44    *p     n        D*
Nov 09 01:53:39 s7924 MMDVM_Reflector[278249]:         DUMP 0010:  02                                                 * *
Nov 09 01:53:39 s7924 MMDVM_Reflector[278249]: [01:53:39 DBG] P25: Received data from 36.21.212.37:55740:
Nov 09 01:53:39 s7924 MMDVM_Reflector[278249]:         DUMP 0000:  80 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    *                *
Nov 09 01:53:39 s7924 MMDVM_Reflector[278249]:         DUMP 0010:  00                                                 * *
Nov 09 01:53:42 s7924 MMDVM_Reflector[278249]: [01:53:42 DBG] P25: Received data from 36.21.212.37:55740:
Nov 09 01:53:42 s7924 MMDVM_Reflector[278249]:         DUMP 0000:  F0 4B 4B 37 4D 55 56 20 20 20 20                   * KK7MUV    *
Nov 09 01:53:42 s7924 MMDVM_Reflector[278249]: [01:53:42 WRN] P25: NACK: KK7MUV; Address: 36.21.212.37:55740; Reason: ACL Rejection
Nov 09 01:53:42 s7924 MMDVM_Reflector[278249]: [01:53:42 DBG] P25: Send data to 36.21.212.37:55740:
Nov 09 01:53:42 s7924 MMDVM_Reflector[278249]:         DUMP 0000:  F0 4B 4B 37 4D 55 56 20 20 20 20                   * KK7MUV    *


Seems like the problem is caused by an ACL format error.

**Comment by firealarmss** [comment]
When you start up the software, does it give any sort of file errors?

**Comment by Zqlucifer** [comment]
When start it says: File not found: ./acl.yml

● mmdvm_reflector.service - MMDVM Reflector Daemon
     Loaded: loaded (/etc/systemd/system/mmdvm_reflector.service; enabled; preset: enabled)
     Active: active (running) since Sun 2024-11-10 05:34:04 UTC; 24s ago
   Main PID: 283363 (MMDVM_Reflector)
      Tasks: 14 (limit: 1053)
     Memory: 33.4M (peak: 33.7M)
        CPU: 605ms
     CGroup: /system.slice/mmdvm_reflector.service
             └─283363 /opt/MMDVM_Reflector/MMDVM_Reflector/bin/Debug/net8.0/MMDVM_Reflector --config=/opt/MMDVM_Reflector/MMDVM_Reflector/configs/config.yml

Nov 10 05:34:04 s7924 systemd[1]: Started mmdvm_reflector.service - MMDVM Reflector Daemon.
Nov 10 05:34:04 s7924 MMDVM_Reflector[283363]: Loading ACL from: ./acl.yml
Nov 10 05:34:04 s7924 MMDVM_Reflector[283363]: File not found: ./acl.yml
Nov 10 05:34:04 s7924 MMDVM_Reflector[283363]: [05:34:04 INF] MMDVM Reflector Suite
Nov 10 05:34:04 s7924 MMDVM_Reflector[283363]:              This software is intended for ham radio use only
Nov 10 05:34:04 s7924 MMDVM_Reflector[283363]:              Copyright 2024 Caleb, KO4UYJ
Nov 10 05:34:05 s7924 MMDVM_Reflector[283363]: [05:34:05 INF] Started Reporter at http://127.0.0.1:3000
Nov 10 05:34:05 s7924 MMDVM_Reflector[283363]: [05:34:05 INF] Starting P25Reflector
Nov 10 05:34:05 s7924 MMDVM_Reflector[283363]: [05:34:05 INF]     Port: 41000
Nov 10 05:34:05 s7924 MMDVM_Reflector[283363]: [05:34:05 INF]     Debug: True
Nov 10 05:34:05 s7924 MMDVM_Reflector[283363]: [05:34:05 INF] P25: Connection opened on port 0.0.0.0:41000.
Nov 10 05:34:05 s7924 MMDVM_Reflector[283363]: [05:34:05 INF] P25Reflector version: 01.00.00 started.
Nov 10 05:34:05 s7924 MMDVM_Reflector[283363]: [05:34:05 INF] Starting YSFReflector
Nov 10 05:34:05 s7924 MMDVM_Reflector[283363]: [05:34:05 INF]     Port: 42000
Nov 10 05:34:05 s7924 MMDVM_Reflector[283363]: [05:34:05 INF]     Debug: False
Nov 10 05:34:05 s7924 MMDVM_Reflector[283363]: [05:34:05 INF] YSF: Connection opened on port 0.0.0.0:42000.
Nov 10 05:34:05 s7924 MMDVM_Reflector[283363]: [05:34:05 INF] YSFReflector version: 01.00.00 started.

**Comment by firealarmss** [comment]
Note in the example config it states **FULL** path to the ACL file. 
`aclPath: "./acl.yml" # Full path to the Access Control file.`
So I would say you probably need to change "./acl.yml" to "/opt/MMDVM_Reflector/MMDVM_Reflector/configs/acl.yml"

**Comment by Zqlucifer** [comment]
Hi, I have confirmed again that my acl file has always been in this directory. I also uploaded the acl file.
![1png](https://github.com/user-attachments/assets/fb6c27a6-2099-45cc-9605-efa37b800f12)
![2](https://github.com/user-attachments/assets/0ed3eada-378f-48b9-b602-8f6ccc082848)
[acl.txt](https://github.com/user-attachments/files/17690395/acl.txt)

**Comment by firealarmss** [comment]
Again, in config.yml you need to specify the entire path to the file.
`aclPath: "/opt/MMDVM_Reflector/MMDVM_Reflector/configs/acl.yml"`
This would be the value in your case.

**Comment by Zqlucifer** [comment]
It's working now, thank you very much for your support!
DE KK7MUV 73!

**Comment by firealarmss** [comment]
Glad its fixed.

**Comment by al-rib** [comment]
Dear sirs

We recommend checking the solar count via -solar in command line.

Thank you,
Andrew
